"""empty message

Revision ID: f61e97ee1bbf
Revises: 1758d84223ba
Create Date: 2017-12-30 14:55:12.737871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f61e97ee1bbf'
down_revision = '1758d84223ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('type', sa.Enum('folder', 'photo', 'video', 'audio', 'pdf', 'txt', 'other'), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'error', 'trash'), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['file.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('content_html', sa.Text(), nullable=False))
    op.alter_column('post', 'slug',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'content_md')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content_md', mysql.TEXT(), nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_1', 'post', 'user', ['user_id'], ['id'])
    op.alter_column('post', 'slug',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.drop_column('post', 'content_html')
    op.drop_table('file')
    # ### end Alembic commands ###
